use bunhead_sweets_db;

insert into Product_categories (name) values ('Torta');
insert into Product_categories (name) values ('Cupcake');
insert into Product_categories (name) values ('Galleta');
insert into Product_categories (name) values ('Brownie');

insert into Products (name, category_id, price, description, image, is_available) values ('Vodka - Smirnoff', 1, 30.4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tellus vestibulum, consequat augue vitae, semper est. Donec gravida nisi ac sem consectetur, nec mollis massa hendrerit. Fusce mi mauris, mollis quis quam eu, consequat faucibus nisl. Maecenas nec quam odio. Integer eget accumsan.', 'http://dummyimage.com/155x100.png/dddddd/000000', true);
insert into Products (name, category_id, price, description, image, is_available) values ('Oneshot Automatic Soap System', 2, 26.92, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tellus vestibulum, consequat augue vitae, semper est. Donec gravida nisi ac sem consectetur, nec mollis massa hendrerit. Fusce mi mauris, mollis quis quam eu, consequat faucibus nisl. Maecenas nec quam odio. Integer eget accumsan.', 'http://dummyimage.com/168x100.png/dddddd/000000', true);
insert into Products (name, category_id, price, description, image, is_available) values ('Sausage - Andouille', 3, 33.68, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tellus vestibulum, consequat augue vitae, semper est. Donec gravida nisi ac sem consectetur, nec mollis massa hendrerit. Fusce mi mauris, mollis quis quam eu, consequat faucibus nisl. Maecenas nec quam odio. Integer eget accumsan.', 'http://dummyimage.com/167x100.png/dddddd/000000', true);
insert into Products (name, category_id, price, description, image, is_available) values ('Sour Puss - Tangerine', 4, 42.23, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tellus vestibulum, consequat augue vitae, semper est. Donec gravida nisi ac sem consectetur, nec mollis massa hendrerit. Fusce mi mauris, mollis quis quam eu, consequat faucibus nisl. Maecenas nec quam odio. Integer eget accumsan.', 'http://dummyimage.com/184x100.png/ff4444/ffffff', true);
insert into Products (name, category_id, price, description, image, is_available) values ('Turnip - White, Organic', 4, 42.7, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tellus vestibulum, consequat augue vitae, semper est. Donec gravida nisi ac sem consectetur, nec mollis massa hendrerit. Fusce mi mauris, mollis quis quam eu, consequat faucibus nisl. Maecenas nec quam odio. Integer eget accumsan.', 'http://dummyimage.com/233x100.png/cc0000/ffffff', true);
insert into Products (name, category_id, price, description, image, is_available) values ('Pastry - Apple Muffins - Mini', 2, 42.67, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tellus vestibulum, consequat augue vitae, semper est. Donec gravida nisi ac sem consectetur, nec mollis massa hendrerit. Fusce mi mauris, mollis quis quam eu, consequat faucibus nisl. Maecenas nec quam odio. Integer eget accumsan.', 'http://dummyimage.com/168x100.png/ff4444/ffffff', true);
insert into Products (name, category_id, price, description, image, is_available) values ('Juice - Mango', 2, 18.52, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tellus vestibulum, consequat augue vitae, semper est. Donec gravida nisi ac sem consectetur, nec mollis massa hendrerit. Fusce mi mauris, mollis quis quam eu, consequat faucibus nisl. Maecenas nec quam odio. Integer eget accumsan.', 'http://dummyimage.com/159x100.png/ff4444/ffffff', true);
insert into Products (name, category_id, price, description, image, is_available) values ('Dr. Pepper - 355ml', 1, 13.12, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tellus vestibulum, consequat augue vitae, semper est. Donec gravida nisi ac sem consectetur, nec mollis massa hendrerit. Fusce mi mauris, mollis quis quam eu, consequat faucibus nisl. Maecenas nec quam odio. Integer eget accumsan.', 'http://dummyimage.com/117x100.png/ff4444/ffffff', true);
insert into Products (name, category_id, price, description, image, is_available) values ('Buffalo - Tenderloin', 1, 42.74, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tellus vestibulum, consequat augue vitae, semper est. Donec gravida nisi ac sem consectetur, nec mollis massa hendrerit. Fusce mi mauris, mollis quis quam eu, consequat faucibus nisl. Maecenas nec quam odio. Integer eget accumsan.', 'http://dummyimage.com/199x100.png/cc0000/ffffff', true);
insert into Products (name, category_id, price, description, image, is_available) values ('Cheese - Swiss', 1, 42.64, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tellus vestibulum, consequat augue vitae, semper est. Donec gravida nisi ac sem consectetur, nec mollis massa hendrerit. Fusce mi mauris, mollis quis quam eu, consequat faucibus nisl. Maecenas nec quam odio. Integer eget accumsan.', 'http://dummyimage.com/206x100.png/dddddd/000000', true);
insert into Products (name, category_id, price, description, image, is_available) values ('Carbonated Water - Blackcherry', 3, 25.97, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tellus vestibulum, consequat augue vitae, semper est. Donec gravida nisi ac sem consectetur, nec mollis massa hendrerit. Fusce mi mauris, mollis quis quam eu, consequat faucibus nisl. Maecenas nec quam odio. Integer eget accumsan.', 'http://dummyimage.com/131x100.png/5fa2dd/ffffff', true);
insert into Products (name, category_id, price, description, image, is_available) values ('Goldschalger', 1, 12.92, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tellus vestibulum, consequat augue vitae, semper est. Donec gravida nisi ac sem consectetur, nec mollis massa hendrerit. Fusce mi mauris, mollis quis quam eu, consequat faucibus nisl. Maecenas nec quam odio. Integer eget accumsan.', 'http://dummyimage.com/202x100.png/5fa2dd/ffffff', true);
insert into Products (name, category_id, price, description, image, is_available) values ('Chicken Giblets', 3, 35.16, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tellus vestibulum, consequat augue vitae, semper est. Donec gravida nisi ac sem consectetur, nec mollis massa hendrerit. Fusce mi mauris, mollis quis quam eu, consequat faucibus nisl. Maecenas nec quam odio. Integer eget accumsan.', 'http://dummyimage.com/128x100.png/cc0000/ffffff', true);
insert into Products (name, category_id, price, description, image, is_available) values ('Soup - Campbells Chili Veg', 4, 46.09, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tellus vestibulum, consequat augue vitae, semper est. Donec gravida nisi ac sem consectetur, nec mollis massa hendrerit. Fusce mi mauris, mollis quis quam eu, consequat faucibus nisl. Maecenas nec quam odio. Integer eget accumsan.', 'http://dummyimage.com/111x100.png/dddddd/000000', true);
insert into Products (name, category_id, price, description, image, is_available) values ('Sultanas', 1, 40.51, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tellus vestibulum, consequat augue vitae, semper est. Donec gravida nisi ac sem consectetur, nec mollis massa hendrerit. Fusce mi mauris, mollis quis quam eu, consequat faucibus nisl. Maecenas nec quam odio. Integer eget accumsan.', 'http://dummyimage.com/146x100.png/ff4444/ffffff', true);
insert into Products (name, category_id, price, description, image, is_available) values ('Pork - Ground', 2, 11.41, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tellus vestibulum, consequat augue vitae, semper est. Donec gravida nisi ac sem consectetur, nec mollis massa hendrerit. Fusce mi mauris, mollis quis quam eu, consequat faucibus nisl. Maecenas nec quam odio. Integer eget accumsan.', 'http://dummyimage.com/190x100.png/5fa2dd/ffffff', true);
insert into Products (name, category_id, price, description, image, is_available) values ('Carbonated Water - Lemon Lime', 2, 42.39, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tellus vestibulum, consequat augue vitae, semper est. Donec gravida nisi ac sem consectetur, nec mollis massa hendrerit. Fusce mi mauris, mollis quis quam eu, consequat faucibus nisl. Maecenas nec quam odio. Integer eget accumsan.', 'http://dummyimage.com/159x100.png/cc0000/ffffff', true);
insert into Products (name, category_id, price, description, image, is_available) values ('Nori Sea Weed', 3, 28.97, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tellus vestibulum, consequat augue vitae, semper est. Donec gravida nisi ac sem consectetur, nec mollis massa hendrerit. Fusce mi mauris, mollis quis quam eu, consequat faucibus nisl. Maecenas nec quam odio. Integer eget accumsan.', 'http://dummyimage.com/137x100.png/ff4444/ffffff', false);
insert into Products (name, category_id, price, description, image, is_available) values ('Flour - Bread', 3, 27.85, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tellus vestibulum, consequat augue vitae, semper est. Donec gravida nisi ac sem consectetur, nec mollis massa hendrerit. Fusce mi mauris, mollis quis quam eu, consequat faucibus nisl. Maecenas nec quam odio. Integer eget accumsan.', 'http://dummyimage.com/221x100.png/ff4444/ffffff', true);
insert into Products (name, category_id, price, description, image, is_available) values ('Mix - Cocktail Strawberry Daiquiri', 3, 34.12, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tellus vestibulum, consequat augue vitae, semper est. Donec gravida nisi ac sem consectetur, nec mollis massa hendrerit. Fusce mi mauris, mollis quis quam eu, consequat faucibus nisl. Maecenas nec quam odio. Integer eget accumsan.', 'http://dummyimage.com/166x100.png/ff4444/ffffff', true);


insert into Users (user_email, first_name, last_name, phone, password, country, city, street, is_admin) values ('javavega@espol.edu.ec', 'Javier', 'Vega', '7684839858', '123', 'Portugal', 'Valongo', '66071 Shopko Park', false);
insert into Users (user_email, first_name, last_name, phone, password, country, city, street, is_admin) values ('faontane@espol.edu.ec', 'Fabrizzio', 'Ontaneda', '2672483288', 'xd', 'Philippines', 'Diadi', '48 Green Ridge Circle', false);
insert into Users (user_email, first_name, last_name, phone, password, country, city, street, is_admin) values ('aaalfran@espol.edu.ec', 'Aaron', 'Franco', '2814904345', '123', 'Nigeria', 'Amper', '0 Brentwood Crossing', false);
insert into Users (user_email, first_name, last_name, phone, password, country, city, street, is_admin) values ('natroram@espol.edu.ec', 'Natalia', 'Ramirez', '7672031247', '123', 'China', 'Sandouping', '520 Grayhawk Parkway', false);
insert into Users (user_email, first_name, last_name, phone, password, country, city, street, is_admin) values ('bunheadsweets@gmail.com', 'Jean', 'Thunderchief', '3412162120', 'admin', 'China', 'Touzao', '7 Jana Center', true);